import './globals.css'
import AuthClient from './components/AuthClient'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthClient children={children} />
    </html>
  )
}
